import type { Metadata } from "next";
import "../globals.css";
import Navbar from "../Components/Navbar/Navbar";
import Footer from "../Components/Footer/Footer";

export const metadata: Metadata = {
  title: "VA Concepts",
  description: "Generated by VA Concepts",
};

export default function BlogLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section>
      <Navbar />

      {children}

      <Footer />
    </section>
  );
}
