import type { Metadata } from "next";
import "../globals.css";
import DesktopNav from "../Components/Navbar/DesktopNav";

export const metadata: Metadata = {
  title: "VA Concepts",
  description: "Generated by VA Concepts",
};

export default function BlogLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return <section>
      <DesktopNav />
      
      {children}</section>
  }
